name: Deploy

on:
  push:
    branches:
      - main
      - prod

jobs:
  test-lint:
    name: Test and lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set vars
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/prod" ]]; then
            echo "prod" > .workspace
          else
            echo "staging" > .workspace
          fi

      - name: Push to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Pushing to ECR..."
          # Insert your ECR push commands here
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          docker build --compress -t ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA .
          docker push ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA
          docker build --compress -t ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA proxy/
          docker push ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA
